	.intel_syntax noprefix
	.globl	_SteamAPI_SetMiniDumpComment
	.def	_SteamAPI_SetMiniDumpComment; .scl	2;	.type	32;	.endef
	
_SteamAPI_SetMiniDumpComment:

	mov eax, 0x11111111
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamAPI_WriteMiniDump
	.def	_SteamAPI_WriteMiniDump; .scl	2;	.type	32;	.endef
	
_SteamAPI_WriteMiniDump:

	mov eax, 0x22222222
	jmp eax
	.p2align 4,,15
	
	
	
	
	
	.globl	_SteamUserStats
	.def	_SteamUserStats; .scl	2;	.type	32;	.endef
	
_SteamUserStats:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamAPI_UnregisterCallResult
	.def	_SteamAPI_UnregisterCallResult; .scl	2;	.type	32;	.endef
	
_SteamAPI_UnregisterCallResult:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamAPI_RegisterCallResult
	.def	_SteamAPI_RegisterCallResult; .scl	2;	.type	32;	.endef
	
_SteamAPI_RegisterCallResult:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamAPI_RunCallbacks
	.def	_SteamAPI_RunCallbacks; .scl	2;	.type	32;	.endef
	
_SteamAPI_RunCallbacks:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	
	.globl	_SteamAPI_RegisterCallback
	.def	_SteamAPI_RegisterCallback; .scl	2;	.type	32;	.endef
	
_SteamAPI_RegisterCallback:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamAPI_UnregisterCallback
	.def	_SteamAPI_UnregisterCallback; .scl	2;	.type	32;	.endef
	
_SteamAPI_UnregisterCallback:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamMatchmaking
	.def	_SteamMatchmaking; .scl	2;	.type	32;	.endef
	
_SteamMatchmaking:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamUtils
	.def	_SteamUtils; .scl	2;	.type	32;	.endef
	
_SteamUtils:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamUser
	.def	_SteamUser; .scl	2;	.type	32;	.endef
	
_SteamUser:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamFriends
	.def	_SteamFriends; .scl	2;	.type	32;	.endef
	
_SteamFriends:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamRemoteStorage
	.def	_SteamRemoteStorage; .scl	2;	.type	32;	.endef
	
_SteamRemoteStorage:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamClient
	.def	_SteamClient; .scl	2;	.type	32;	.endef
	
_SteamClient:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamAPI_Init
	.def	_SteamAPI_Init; .scl	2;	.type	32;	.endef
	
_SteamAPI_Init:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamAPI_Shutdown
	.def	_SteamAPI_Shutdown; .scl	2;	.type	32;	.endef
	
_SteamAPI_Shutdown:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamNetworking
	.def	_SteamNetworking; .scl	2;	.type	32;	.endef
	
_SteamNetworking:

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.globl	_SteamApps 
	.def	_SteamApps; .scl	2;	.type	32;	.endef
	
_SteamApps :

	mov eax, 0x12345678
	jmp eax
	.p2align 4,,15
	
	
	
	
	.section .drectve
	.ascii " -export:\"SteamAPI_SetMiniDumpComment\""
	.ascii " -export:\"SteamAPI_WriteMiniDump\""
	.ascii " -export:\"SteamUserStats\""
	.ascii " -export:\"SteamAPI_UnregisterCallResult\""
	.ascii " -export:\"SteamAPI_RegisterCallResult\""
	.ascii " -export:\"SteamAPI_RunCallbacks\""
	.ascii " -export:\"SteamAPI_RegisterCallback\""
	.ascii " -export:\"SteamAPI_UnregisterCallback\""
	.ascii " -export:\"SteamMatchmaking\""
	.ascii " -export:\"SteamUtils\""
	.ascii " -export:\"SteamUser\""
	.ascii " -export:\"SteamFriends\""
	.ascii " -export:\"SteamRemoteStorage\""
	.ascii " -export:\"SteamClient\""
	.ascii " -export:\"SteamAPI_Init\""
	.ascii " -export:\"SteamAPI_Shutdown\""
	.ascii " -export:\"SteamNetworking\""
	.ascii " -export:\"SteamApps\""
	

	
	

	
	